title: Aristotle
description: "[Insert tagline here]"
url: "https://aristotle.games"
baseurl: ""

# Build settings
markdown: kramdown
permalink: /blog/:year/:month/:day/:title/

# Exclude from build
exclude:
  - README.md
  - Gemfile
  - Gemfile.lock
